### ISSUE TITLE
Syntax Errors

### ISSUE THREAD

**Issue by tmcnelley** [ryan-d-williams/MMM-GoogleSheets#29]
My Google Sheet isn't loading; My MM shows the header title but then all I get is loading.... Here is the error:
[25.09.2023 13:16.37.918] [LOG]   ====================== Starting node_helper for module [MMM-GoogleSheets]
[25.09.2023 13:16.37.918] [LOG]   Sockets connected & modules started ...
[25.09.2023 13:16.37.941] [LOG]   Launching application.
[13665:0925/131638.476499:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[13673:0925/131638.600688:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[25.09.2023 13:16.39.869] [INFO]  Checking git for module: MMM-GoogleSheets
[25.09.2023 13:16.39.946] [INFO]  Checking git for module: MagicMirror
[25.09.2023 13:16.40.688] [ERROR] Whoops! There was an uncaught exception...
[25.09.2023 13:16.40.694] [ERROR] SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Request._callback (/home/dashboard/MagicMirror/modules/MMM-GoogleSheets/node_helper.js:47:27)
    at self.callback (/home/dashboard/MagicMirror/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/home/dashboard/MagicMirror/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/home/dashboard/MagicMirror/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[25.09.2023 13:16.40.694] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[25.09.2023 13:16.40.694] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[25.09.2023 13:19.13.465] [LOG]   Shutting down server...
[25.09.2023 13:19.13.466] [LOG]   Stopping module helper: updatenotification
[25.09.2023 13:19.13.466] [LOG]   Stopping module helper: MMM-GoogleSheets
[25.09.2023 13:19.13.467] [LOG]   Node_helpers stopped ...

**Comment by tmcnelley** [comment]
If I try and launch the website deployment via the URL from a browser, this is the error I get within the browser page:

TypeError: Cannot read properties of undefined (reading '0') (line 11, file "Code")

I'm guessing the code and script properties are not talking to each other and it doesn't know what to do with the Function code for MMM_GoogleSheets?

**Comment by brandonfake69** [comment]
Getting the same thing.

**Comment by tmcnelley** [comment]
Is anyone monitoring this module?

**Comment by ryan-d-williams** [comment]
@brandonfake69 @tmcnelley 

@tmcnelley intermittently monitoring!

If you try to launch the url directly in your browser you will get an error. This is because you are not supplying the parameters necessary to get the data. In other words, if you use the url directly, it tries to parse out the sheet name and range data and it fails to do so.

If you want to be able to use the url directly to see the data response you need to format the url correctly with GET parameters. For example, something like:
`[URL]?sheet=[your sheet name parameter]&range=[your range parameter]`

You can actually see how this url is built in the MM module `node_helper.js` line 39

I'm going to go ahead and close this. Feel free to open it back up if you have further issues!

**Comment by tmcnelley** [comment]
Thank you Ryan for replying..I understand your explanation on the URL attempt..but the first error (first entry in this issue) isn't being launched from the URL - it's being launched within Magic Mirror. I only received the URL errors after I was troubleshooting..looking for additional information.
How do I address the error within Magic Mirror?

**Comment by ryan-d-williams** [comment]
@tmcnelley I was confused thanks for the clarification. I can help you look through it but I'll need to see your configuration. If your data is sensitive and you don't want me to see your google sheet then please don't send it. Do you mind sending the configuration you're using?

**Comment by tmcnelley** [comment]
@ryan-d-williams - thank you Ryan - I will gather my configs and post here.

**Comment by tmcnelley** [comment]
[config.txt](https://github.com/ryan-d-williams/MMM-GoogleSheets/files/12784959/config.txt)
@ryan-d-williams - here is my config.js file.
thank you for reviewing.

**Comment by ryan-d-williams** [comment]
@tmcnelley your issue is with the "sheet" parameter. That should be the name of the sheet you want to get the data from, not the file name. You have used "test" which is not a sheet name in your document. I swapped that to "sheet1" (the default sheet name) and was able to see the data without any problems.

**Comment by tmcnelley** [comment]
Wow!!! Thank you for detecting that silly error on my part. I appreciate your willingness to troubleshoot my lack of awareness in my code.

**Comment by ryan-d-williams** [comment]
No problem! I have actually been thinking about adding better error messages for these kinds of situations (if you look at past issues it is a common problem).

Happy to help!
